apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/nifty-yeti-164407/gke-base
deploy:
  kubectl:
    manifests:
      - kubernetes/pod*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: nifty-yeti-164407
