apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/nifty-yeti-164407/gke-base
    workspace: .
    docker:
        # Dockerfile's location relative to workspace. Defaults to "Dockerfile"
        dockerfilePath: kubernetes/Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/*.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: nifty-yeti-164407
